### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by dredav** [InsonusK/get-latest-release#5]
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/Show less

**Comment by NishaSharma14** [comment]
Thanks, @dredav for raising this issue.

I am getting the same warning too.

`Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

**Comment by InsonusK** [comment]
I have update packages, this problem must be gone automaticaly. But as I understand that there is some problem in code.

https://github.com/actions/toolkit/issues/1218
